# Generated by Django 2.1.4 on 2018-12-04 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eproperty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertyImage', models.ImageField(blank=True, null=True, upload_to='')),
                ('propertyImageID', models.CharField(max_length=300)),
                ('propertyImageDescription', models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='propertyimage',
            name='property',
        ),
        migrations.RemoveField(
            model_name='property',
            name='id',
        ),
        migrations.AddField(
            model_name='property',
            name='propertyID',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='PropertyImage',
        ),
        migrations.AddField(
            model_name='propertyimages',
            name='propertyID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eproperty.Property'),
        ),
    ]
