# Generated by Django 2.1.4 on 2018-12-04 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eproperty', '0002_auto_20181204_0640'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'City'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Country'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'Property'},
        ),
        migrations.AlterModelOptions(
            name='propertycategory',
            options={'verbose_name_plural': 'PropertyCategory'},
        ),
        migrations.AlterModelOptions(
            name='propertyfacing',
            options={'verbose_name_plural': 'PropertyFacing'},
        ),
        migrations.AlterModelOptions(
            name='propertyimages',
            options={'verbose_name_plural': 'PropertyImages'},
        ),
        migrations.AlterModelOptions(
            name='propertysector',
            options={'verbose_name_plural': 'PropertySector'},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'verbose_name_plural': 'Province'},
        ),
    ]
