# Generated by Django 2.1.4 on 2018-12-04 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eproperty', '0003_auto_20181204_0701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='propertyCategory',
        ),
        migrations.RemoveField(
            model_name='property',
            name='propertyCity',
        ),
        migrations.RemoveField(
            model_name='property',
            name='propertyCountry',
        ),
        migrations.RemoveField(
            model_name='property',
            name='propertyFacing',
        ),
        migrations.RemoveField(
            model_name='property',
            name='propertyProvince',
        ),
        migrations.RemoveField(
            model_name='property',
            name='propertySector',
        ),
        migrations.RemoveField(
            model_name='propertyimages',
            name='propertyID',
        ),
        migrations.DeleteModel(
            name='Property',
        ),
        migrations.DeleteModel(
            name='PropertyImages',
        ),
    ]
