# Generated by Django 2.1.4 on 2018-12-04 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eproperty', '0004_auto_20181204_0745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertyTitle', models.CharField(max_length=100)),
                ('propertyStreet', models.CharField(max_length=50)),
                ('propertyPostalCode', models.CharField(max_length=6)),
                ('propertyStreetNumber', models.CharField(max_length=5)),
                ('propertyConstructionDate', models.DateField()),
                ('propertyRegistrationDate', models.DateField()),
                ('propertyNumberOfHalls', models.IntegerField()),
                ('propertyNumberOfRooms', models.IntegerField()),
                ('propertyNumberOfBathrooms', models.FloatField()),
                ('propertyNumberOfFloors', models.IntegerField()),
                ('propertyTotalArea', models.FloatField()),
                ('propertyAskingPrice', models.FloatField()),
                ('propertySellingPrice', models.FloatField()),
                ('propertyCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eproperty.PropertyCategory')),
                ('propertyCity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eproperty.City')),
                ('propertyCountry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eproperty.Country')),
                ('propertyFacing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eproperty.PropertyFacing')),
                ('propertyProvince', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eproperty.Province')),
                ('propertySector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eproperty.PropertySector')),
            ],
            options={
                'verbose_name_plural': 'Property',
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertyImageDescription', models.CharField(max_length=100)),
                ('propertyImage', models.ImageField(blank=True, null=True, upload_to='')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eproperty.Property')),
            ],
            options={
                'verbose_name_plural': 'PropertyImage',
            },
        ),
    ]
