# Generated by Django 2.1.4 on 2018-12-05 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eproperty', '0005_property_propertyimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='propertyAskingPrice',
            field=models.FloatField(default=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='propertyConstructionDate',
            field=models.DateField(default=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='propertyNumberOfBathrooms',
            field=models.FloatField(default=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='propertyNumberOfFloors',
            field=models.IntegerField(default=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='propertyNumberOfHalls',
            field=models.IntegerField(default=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='propertyNumberOfRooms',
            field=models.IntegerField(default=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='propertyRegistrationDate',
            field=models.DateField(default=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='propertySellingPrice',
            field=models.FloatField(default=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='propertyTotalArea',
            field=models.FloatField(default=True),
        ),
    ]
